"""compelete schema

Revision ID: 1a60b020c31a
Revises: e068a6954461
Create Date: 2026-06-19 11:31:41.770869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a60b020c31a'
down_revision: Union[str, Sequence[str], None] = 'e068a6954461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explorer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('available_xp', sa.Integer(), nullable=False),
    sa.Column('cumulative_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('plan_tier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interest_tags', postgresql.ARRAY(sa.String()), nullable=True, comment="User's selected interests like 'history', 'foodie', 'outdoors'."),
    sa.Column('budget_preference', sa.String(), nullable=True, comment="User's budget preference, e.g., 'low', 'medium', 'high'."),
    sa.Column('preferred_travel_style', sa.String(), nullable=True, comment="e.g., 'solo', 'family', 'couple', 'group'."),
    sa.Column('home_city', sa.String(), nullable=True, comment="User's home city for 'near me' features."),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explorer_profiles_account_id'), 'explorer_profiles', ['account_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('government', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lattitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('geofence_radius', sa.Integer(), nullable=True),
    sa.Column('Created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_uuid')
    )
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True, comment='Foreign key to the accounts table.'),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('government', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lattitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('geofence_radius', sa.Integer(), nullable=True),
    sa.Column('address_url', sa.String(), nullable=True, comment='URL to the location on a map, e.g., Google Maps link.'),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object describing opening hours.'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Foreign key to a categories table for vendors.'),
    sa.Column('is_approved', sa.Boolean(), nullable=False, comment='Whether the vendor is approved and visible.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_profiles_account_id'), 'vendor_profiles', ['account_id'], unique=False)
    op.create_table('places_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_uuid', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('explorer_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('Created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_uuid')
    )
    op.create_index(op.f('ix_places_reviews_id'), 'places_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_places_reviews_place_id'), 'places_reviews', ['place_id'], unique=False)
    op.create_table('vendor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_reviews_id'), 'vendor_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_reviews_vendor_id'), 'vendor_reviews', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_reviews_vendor_id'), table_name='vendor_reviews')
    op.drop_index(op.f('ix_vendor_reviews_id'), table_name='vendor_reviews')
    op.drop_table('vendor_reviews')
    op.drop_index(op.f('ix_places_reviews_place_id'), table_name='places_reviews')
    op.drop_index(op.f('ix_places_reviews_id'), table_name='places_reviews')
    op.drop_table('places_reviews')
    op.drop_index(op.f('ix_vendor_profiles_account_id'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_explorer_profiles_account_id'), table_name='explorer_profiles')
    op.drop_table('explorer_profiles')
    # ### end Alembic commands ###
