"""fix vendor maps id column case

Revision ID: d517a2b50227
Revises: 1a60b020c31a
Create Date: 2026-06-20 09:07:20.073043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd517a2b50227'
down_revision: Union[str, Sequence[str], None] = '1a60b020c31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('Maps_id', sa.String(), nullable=True, comment='Google Maps Place ID for the vendor.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'Maps_id')
    # ### end Alembic commands ###
